### ISSUE TITLE
KDE automatic screen locking should be disabled.

### ISSUE THREAD

**Issue by petterreinholdtsen** [malinkb/skolelinux-dugnad-for-Ukraina#11]
After 5 minutes of inactivity, the KDE screen locker kick in and demand password to get back into the system.  This do not make sense in kiosk mode, where the KDE session start automatically at boot and logout, but not if the system is left alone for five minutes.  Note, due to a publicly known password (see #10), users can be expected to be able to enter the password to unlock the screen, so locking the screen do not provide any sensible advantages.

**Comment by petterreinholdtsen** [comment]
I suspect running something like `in-target su - ukraina -c "kwriteconfig5 --file kscreensaverrc --group Daemon --key Autolock false` in the preseed/late_command step might solve the locking issue, but this change is untested.

**Comment by malinkb** [comment]
I think we should test it and if that works, we merge it in

**Comment by petterreinholdtsen** [comment]
It is tested and works, but had a small typo.  The filename is kscreenlockerrc.
