### ISSUE TITLE
Should firmware-b43-installer be in non-free-firmware?

### ISSUE THREAD

**Issue by petterreinholdtsen** [malinkb/skolelinux-dugnad-for-Ukraina#4]
In README.md, there is a comment about firmware-b43-installer currently being part of the contrib apt component while it is said that it really belong to non-free-firmware.  The reason it is not in non-free-firmware is that the package is an empty shell, not a firmware package.  The package contain scripts that will download the firmware from the Internet, because the copyright holders of the firmware prohibit third party distribution of the firmware binary blob.  This make it impossible to install this
firmware using a ISO containing the firmware-b43-installer package, and make it hard to preseed automatic installation
of the package when the blueray (*-BD-*.iso) images are used to install.

Pehraps the comment in the README should be rephrased?

**Comment by malinkb** [comment]
Is there a way to omit it and include the firmware it installs somewhere so it's easier to get wifi cards depending on this firmware to work out of the box?

**Comment by petterreinholdtsen** [comment]
[malinkb]
> Is there a way to omit it and include the firmware it installs
> somewhere so it's easier to get wifi cards depending on this firmware
> to work out of the box?

No idea, but assume providing the firmware outside the control of the
copyright holder would be breaking the law, so have no intention to
investigate.

I syspect a more useful approach might be to fix resolv.conf and
sources.list early in the installation to be able to install the package
if Internet is available.  At the moment resolv.conf is fixed after
boot, and sources.list is fixed just before boot to the hard drive.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by malinkb** [comment]
That sounds like a good idea and will make it possible to install the driver during installation, at least if it is possible to connect the computer to Ethernet and the Ethernet does have supported firmware
